[workspace]
git_only = true
publish = false
release_always = false
git_release_enable = false
git_tag_name = "{{ package }}-v{{ version }}"
pr_branch_prefix = "release-plz/"
pr_name = "chore: release"
dependencies_update = true
